# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3a99fa0df5b0985726a3fc32dc4cc3d7083ea45aa6b56530bf1063c681d89be1bb6b976efcad70fad24fb259c3d60513dde6e587f74b1c4e1b01996549a1f6e

test:
  secret_key_base: 6f8bfb166c84635524b9d91267e351e95b9ba16d5238bfbaeb37d58b4cbfcf6af359b4869d7eba505a1fa8c6ad85e246c8875a56be7b394f6b9b70160d47683c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
